log-etl:
  pipeline:
    bufferSize: 100
    prefetchSize: 10
    parallelism: 4

spring:
  datasource:
    url: jdbc:mysql://localhost:33061/logdatabase
    username: logwriter
    password: logwriter