CREATE TABLE `BLACKLISTED_IPS` (
  `ID` bigint(10) NOT NULL AUTO_INCREMENT,
  `IP_ADDRESS` varchar(45) NOT NULL,
  `START_DATE` datetime(3) NOT NULL,
  `END_DATE` datetime(3) NOT NULL,
  `NUM_ACCESS` int(11) NOT NULL,
  `MESSAGE` varchar(300) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IP_ADDRESS_IX` (`IP_ADDRESS`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1;
