log_database:
  restart: always
  image: mysql:5.7
  ports:
    - 33061:3306
  environment:
    MYSQL_DATABASE: logdatabase
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: logwriter
    MYSQL_PASSWORD: logwriter
  volumes:
   - ./mysql_data:/var/lib/mysql
   - ./init-scripts:/docker-entrypoint-initdb.d